### ISSUE TITLE
Webpacker not working rails 6

### ISSUE THREAD

**Issue by IvRRimum** [blocknotes/activeadmin_blaze_theme#8] opened 2021-05-06 01:02 UTC
Rails 6.0.3.5
3.0.0

My `app/javascript/packs/active_admin.js`

```

// Load Active Admin's styles into Webpacker,
// see `active_admin.scss` for customization.
import "../stylesheets/active_admin";

import "@activeadmin/activeadmin";

require('activeadmin_blaze_theme');
```

But the design doesnt change..

**Comment by IvRRimum** [comment] 2021-05-06 01:15
When doing a deploy to production
`ModuleNotFoundError: Module not found: Error: Can't resolve 'activeadmin_blaze_theme' in '`

**Comment by blocknotes** [comment] 2021-05-10 08:33
Hey @IvRRimum
The webpacker support is still experimental ATM.

I have just prepared a release with it (it was in the master branch only for the last week).

I made a test locally (with production conf) and it works using:
- `compile: true` option set in _config/webpacker.yml_ - in the _production_ block;
- `RAILS_ENV=production RAILS_SERVE_STATIC_FILES=1  bin/rails s`

To troubleshoot you could:
- remove _node_modules_ folder and run again `yarn`;
- run `bin/rails tmp:clear` to clear the tmp files;
- share some production logs otherwise.

**Comment by blocknotes** [comment] 2021-05-30 12:00
Closing for missing feedback - feel free to re-open it if the issue is not solved

**Closed by blocknotes** 2021-05-30 12:00 UTC
